// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWWsvaxZTDbyHNwsKkWqOPFQN2cmr0yZw',
    appId: '1:57551580159:web:208bc9874e98ea32f315ca',
    messagingSenderId: '57551580159',
    projectId: 'olx-clone-2e45f',
    authDomain: 'olx-clone-2e45f.firebaseapp.com',
    storageBucket: 'olx-clone-2e45f.appspot.com',
    measurementId: 'G-8HEVT3D041',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA1tHgfMn07DBeI2bZKNHUrVgjPD_sEb0',
    appId: '1:57551580159:android:5ac54c44aefae648f315ca',
    messagingSenderId: '57551580159',
    projectId: 'olx-clone-2e45f',
    storageBucket: 'olx-clone-2e45f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0icaLyZ2oC5I6x9BWdK6aEChUg-o8bzI',
    appId: '1:57551580159:ios:1888bae845acb7e1f315ca',
    messagingSenderId: '57551580159',
    projectId: 'olx-clone-2e45f',
    storageBucket: 'olx-clone-2e45f.appspot.com',
    iosBundleId: 'com.example.olx',
  );
}
